//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesMerCa.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GesMerCa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap acercaDe {
            get {
                object obj = ResourceManager.GetObject("acercaDe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddNodefromFile_354 {
            get {
                object obj = ResourceManager.GetObject("AddNodefromFile_354", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ArrangeWindowsHS {
            get {
                object obj = ResourceManager.GetObject("ArrangeWindowsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap base_picture_32 {
            get {
                object obj = ResourceManager.GetObject("base_picture_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar.
        /// </summary>
        public static string btnActivar {
            get {
                return ResourceManager.GetString("btnActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btnClose {
            get {
                object obj = ResourceManager.GetObject("btnClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar imagen.
        /// </summary>
        public static string btnLoginGuardarImagen {
            get {
                return ResourceManager.GetString("btnLoginGuardarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cargaInicio2 {
            get {
                object obj = ResourceManager.GetObject("cargaInicio2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cargando {
            get {
                object obj = ResourceManager.GetObject("cargando", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cart {
            get {
                object obj = ResourceManager.GetObject("cart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CascadeWindows {
            get {
                object obj = ResourceManager.GetObject("CascadeWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Close_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("Close_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ClosePreviewHH {
            get {
                object obj = ResourceManager.GetObject("ClosePreviewHH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol usuario.
        /// </summary>
        public static string cmbRolUsuario {
            get {
                return ResourceManager.GetString("cmbRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap codebar {
            get {
                object obj = ResourceManager.GetObject("codebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap contacts {
            get {
                object obj = ResourceManager.GetObject("contacts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dolly {
            get {
                object obj = ResourceManager.GetObject("dolly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit_Redo {
            get {
                object obj = ResourceManager.GetObject("Edit_Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit_Undo {
            get {
                object obj = ResourceManager.GetObject("Edit_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filtroOn {
            get {
                object obj = ResourceManager.GetObject("filtroOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fondoAcercaDe {
            get {
                object obj = ResourceManager.GetObject("fondoAcercaDe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap foto_CV {
            get {
                object obj = ResourceManager.GetObject("foto_CV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Stump-based 24x24 discrete(?) adaboost frontal face detector.
        ///    Created by Rainer Lienhart.
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///                        Intel License Agreeme [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string haarcascade_frontalface_default {
            get {
                return ResourceManager.GetString("haarcascade_frontalface_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconoMsgTriangulo {
            get {
                object obj = ResourceManager.GetObject("IconoMsgTriangulo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap locked {
            get {
                object obj = ResourceManager.GetObject("locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logoSanJose {
            get {
                object obj = ResourceManager.GetObject("logoSanJose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap magnifyingglass {
            get {
                object obj = ResourceManager.GetObject("magnifyingglass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JPEG imágenes (*.jpeg)|*.jpeg|PNG imágenes (*.png)|*.png|JPG imágenes (*.jpg)|*.jpg|GIF imágenes (*.gif)|*.gif|Todos los archivos|*.*.
        /// </summary>
        public static string msgAbrirImagenUsuario {
            get {
                return ResourceManager.GetString("msgAbrirImagenUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir imagen usuario.
        /// </summary>
        public static string msgAbrirImagenUsuarioTitulo {
            get {
                return ResourceManager.GetString("msgAbrirImagenUsuarioTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de {0}.
        /// </summary>
        public static string msgAcercaDeTitulo {
            get {
                return ResourceManager.GetString("msgAcercaDeTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha modificado ningún registro de la base de datos.
        /// </summary>
        public static string msgAltaOpcSinModificaciones {
            get {
                return ResourceManager.GetString("msgAltaOpcSinModificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los valores de dominio deben estar separados por ;.
        /// </summary>
        public static string msgAltaOpcValoresDominio {
            get {
                return ResourceManager.GetString("msgAltaOpcValoresDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF no válido.
        /// </summary>
        public static string msgAltaProveedorCif {
            get {
                return ResourceManager.GetString("msgAltaProveedorCif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha modificado ningún registro de la base de datos.
        /// </summary>
        public static string msgAltaProveedorError {
            get {
                return ResourceManager.GetString("msgAltaProveedorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener un CIF/NIF.
        /// </summary>
        public static string msgAltaProveedorErrorCif {
            get {
                return ResourceManager.GetString("msgAltaProveedorErrorCif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener un CIF válido.
        /// </summary>
        public static string msgAltaProveedorErrorCifValido {
            get {
                return ResourceManager.GetString("msgAltaProveedorErrorCifValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener una dirección.
        /// </summary>
        public static string msgAltaProveedorErrorDireccion {
            get {
                return ResourceManager.GetString("msgAltaProveedorErrorDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha includo un email.
        /// </summary>
        public static string msgAltaProveedorErrorEmail {
            get {
                return ResourceManager.GetString("msgAltaProveedorErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha incluido ninguna observación.
        /// </summary>
        public static string msgAltaProveedorErrorObs {
            get {
                return ResourceManager.GetString("msgAltaProveedorErrorObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener el nombre del proveedor.
        /// </summary>
        public static string msgAltaProveedorErrorProv {
            get {
                return ResourceManager.GetString("msgAltaProveedorErrorProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha incluido un téléfono.
        /// </summary>
        public static string msgAltaProveedorErrorTlf {
            get {
                return ResourceManager.GetString("msgAltaProveedorErrorTlf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha incluido página web.
        /// </summary>
        public static string msgAltaProveedorErrorWeb {
            get {
                return ResourceManager.GetString("msgAltaProveedorErrorWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIF no válido.
        /// </summary>
        public static string msgAltaProveedorNif {
            get {
                return ResourceManager.GetString("msgAltaProveedorNif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nuevo proveedor ha sido grabado correctamente.
        /// </summary>
        public static string msgAltaProveedorOK {
            get {
                return ResourceManager.GetString("msgAltaProveedorOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha creado el usuario, ID: {0}.
        /// </summary>
        public static string msgAltaUsuario {
            get {
                return ResourceManager.GetString("msgAltaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compruebe los datos del usuario.
        /// </summary>
        public static string msgAltaUsuarioComp {
            get {
                return ResourceManager.GetString("msgAltaUsuarioComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos incorrectos o insuficiones.
        /// </summary>
        public static string msgAltaUsuarioCompTitulo {
            get {
                return ResourceManager.GetString("msgAltaUsuarioCompTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de email es inválida.
        /// </summary>
        public static string msgAltaUsuarioErrorEmail {
            get {
                return ResourceManager.GetString("msgAltaUsuarioErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario con este nombre de usuario.
        /// </summary>
        public static string msgAltaUsuarioErrorLogin {
            get {
                return ResourceManager.GetString("msgAltaUsuarioErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string msgAltaUsuarioErrorPass {
            get {
                return ResourceManager.GetString("msgAltaUsuarioErrorPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca sus credenciales para desbloquear el terminal.
        /// </summary>
        public static string msgBloqueoAccesoIntroDesblq {
            get {
                return ResourceManager.GetString("msgBloqueoAccesoIntroDesblq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este terminal ha sido bloqueado. Introduzca su clave de acceso para desbloquearlo..
        /// </summary>
        public static string msgBloqueoAccesoTTSInfo {
            get {
                return ResourceManager.GetString("msgBloqueoAccesoTTSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido establecer conexión con la BD.
        ///
        ///¿Desea reintentar la conexión?.
        /// </summary>
        public static string msgCargaInicioErrorBD {
            get {
                return ResourceManager.GetString("msgCargaInicioErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error conexión BD.
        /// </summary>
        public static string msgCargaInicioErrorBDTitulo {
            get {
                return ResourceManager.GetString("msgCargaInicioErrorBDTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido establecer la conexión a Internet.
        ///
        ///¿Desea reintentar la conexión?.
        /// </summary>
        public static string msgCargaInicioErrorInternet {
            get {
                return ResourceManager.GetString("msgCargaInicioErrorInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error conexión Internet.
        /// </summary>
        public static string msgCargaInicioErrorInternetTitulo {
            get {
                return ResourceManager.GetString("msgCargaInicioErrorInternetTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallida.
        /// </summary>
        public static string msgCargaInicioFallida {
            get {
                return ResourceManager.GetString("msgCargaInicioFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error en la grabación de la nueva opción de usuario, inténtelo de nuevo.
        /// </summary>
        public static string msgConfigOpcErrorGrabacion {
            get {
                return ResourceManager.GetString("msgConfigOpcErrorGrabacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error grabación nueva opción.
        /// </summary>
        public static string msgConfigOpcErrorGrabacionTitulo {
            get {
                return ResourceManager.GetString("msgConfigOpcErrorGrabacionTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha grabado la opción correctamente.
        /// </summary>
        public static string msgConfigOpcOK {
            get {
                return ResourceManager.GetString("msgConfigOpcOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción modificada.
        /// </summary>
        public static string msgConfigOpcOKTitulo {
            get {
                return ResourceManager.GetString("msgConfigOpcOKTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las opciones del usuario que no se hayan personalizado, corresponderán a las generales.
        /// </summary>
        public static string msgConfigOpcUsuario {
            get {
                return ResourceManager.GetString("msgConfigOpcUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones de usuario.
        /// </summary>
        public static string msgConfigOpcUsuarioTitulo {
            get {
                return ResourceManager.GetString("msgConfigOpcUsuarioTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener una descripción para la opción.
        /// </summary>
        public static string msgControlErrorAltaOpcDescripcion {
            get {
                return ResourceManager.GetString("msgControlErrorAltaOpcDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener el rango de valores de la opción.
        /// </summary>
        public static string msgControlErrorAltaOpcDominio {
            get {
                return ResourceManager.GetString("msgControlErrorAltaOpcDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener el nombre de la opción.
        /// </summary>
        public static string msgControlErrorAltaOpcPropiedad {
            get {
                return ResourceManager.GetString("msgControlErrorAltaOpcPropiedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener el título de la opción.
        /// </summary>
        public static string msgControlErrorAltaOpcTitulo {
            get {
                return ResourceManager.GetString("msgControlErrorAltaOpcTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener un valor incial de la opción.
        /// </summary>
        public static string msgControlErrorAltaOpcValor {
            get {
                return ResourceManager.GetString("msgControlErrorAltaOpcValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca una contraseña.
        /// </summary>
        public static string msgControlErroresPassword {
            get {
                return ResourceManager.GetString("msgControlErroresPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca un nombre de usuario.
        /// </summary>
        public static string msgControlErroresUsuario {
            get {
                return ResourceManager.GetString("msgControlErroresUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar el usuario .
        /// </summary>
        public static string msgEliminarUsuario {
            get {
                return ResourceManager.GetString("msgEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar usuario.
        /// </summary>
        public static string msgEliminarUsuarioTitulo {
            get {
                return ResourceManager.GetString("msgEliminarUsuarioTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea guardar los cambios del usuario .
        /// </summary>
        public static string msgGuardarCambiosUsuario {
            get {
                return ResourceManager.GetString("msgGuardarCambiosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar usuario.
        /// </summary>
        public static string msgGuardarCambiosUsuarioTitulo {
            get {
                return ResourceManager.GetString("msgGuardarCambiosUsuarioTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha detectado que hay imágenes del usuario anteriores almacenadas en el sistema.
        ///¿Desea eliminarlas y así reiniciar el sistema de reconocimiento?.
        /// </summary>
        public static string msgGuardarImagenesLoginFacial {
            get {
                return ResourceManager.GetString("msgGuardarImagenesLoginFacial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reinicio del sistema de reconocimiento.
        /// </summary>
        public static string msgGuardarImagenesLoginFacialTitulo {
            get {
                return ResourceManager.GetString("msgGuardarImagenesLoginFacialTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ha sido iniciado. Por favor, inicie sesión para comenzar.
        /// </summary>
        public static string msgInfoTTS_1 {
            get {
                return ResourceManager.GetString("msgInfoTTS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido .
        /// </summary>
        public static string msgInfoTTS_2 {
            get {
                return ResourceManager.GetString("msgInfoTTS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error en la aplicación.
        ///
        ///Informe al administrador de sistemas fecha y hora para comprobar el registro..
        /// </summary>
        public static string msgInicioErrorGeneral {
            get {
                return ResourceManager.GetString("msgInicioErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general.
        /// </summary>
        public static string msgInicioErrorGeneralTitulo {
            get {
                return ResourceManager.GetString("msgInicioErrorGeneralTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea continuar almacenando imágenes del usuario?.
        /// </summary>
        public static string msgLoginAlmacenarImagenCamara {
            get {
                return ResourceManager.GetString("msgLoginAlmacenarImagenCamara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminar de almacenar imágenes.
        /// </summary>
        public static string msgLoginAlmacenarImagenCamaraTitulo {
            get {
                return ResourceManager.GetString("msgLoginAlmacenarImagenCamaraTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string msgLoginCodigo {
            get {
                return ResourceManager.GetString("msgLoginCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la carga de las opciones del usuario. Se utilizarán las generales.
        /// </summary>
        public static string msgLoginErrorCargaOpciones {
            get {
                return ResourceManager.GetString("msgLoginErrorCargaOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la carga de las opciones del usuario.
        /// </summary>
        public static string msgLoginErrorCargaOpcionesTitulo {
            get {
                return ResourceManager.GetString("msgLoginErrorCargaOpcionesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha excedido el número de intentos..
        /// </summary>
        public static string msgLoginErrorMaxIntentosTexto {
            get {
                return ResourceManager.GetString("msgLoginErrorMaxIntentosTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excedido número de intentos.
        /// </summary>
        public static string msgLoginErrorMaxIntentosTitulo {
            get {
                return ResourceManager.GetString("msgLoginErrorMaxIntentosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe activarse en modo administración de rostros de usuarios..
        /// </summary>
        public static string msgLoginErrorSinImagenUss {
            get {
                return ResourceManager.GetString("msgLoginErrorSinImagenUss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la detección de rostro.
        /// </summary>
        public static string msgLoginErrorSinImagenUssTitulo {
            get {
                return ResourceManager.GetString("msgLoginErrorSinImagenUssTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña inválidos.
        ///
        ///Dispone de {0} intentos..
        /// </summary>
        public static string msgLoginErrorTexto {
            get {
                return ResourceManager.GetString("msgLoginErrorTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login inválido.
        /// </summary>
        public static string msgLoginErrorTitulo {
            get {
                return ResourceManager.GetString("msgLoginErrorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha añadido una nueva imagen del usuario..
        /// </summary>
        public static string msgLoginNuevaImagenUss {
            get {
                return ResourceManager.GetString("msgLoginNuevaImagenUss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen de usuario capturada.
        /// </summary>
        public static string msgLoginNuevaImagenUssTitulo {
            get {
                return ResourceManager.GetString("msgLoginNuevaImagenUssTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona desconocida.
        /// </summary>
        public static string msgLoginPersonaDesconocida {
            get {
                return ResourceManager.GetString("msgLoginPersonaDesconocida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona detectada.
        /// </summary>
        public static string msgLoginPersonaDetectada {
            get {
                return ResourceManager.GetString("msgLoginPersonaDetectada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nueva opción se ha grabado correctamente.
        /// </summary>
        public static string msgNuevaOpcionOK {
            get {
                return ResourceManager.GetString("msgNuevaOpcionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario/Contraseña no puede ser null/vacío.
        /// </summary>
        public static string msgObjUssError {
            get {
                return ResourceManager.GetString("msgObjUssError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creación usuario.
        /// </summary>
        public static string msgObjUssErrorTitulo {
            get {
                return ResourceManager.GetString("msgObjUssErrorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un módulo con el nombre indicado.
        /// </summary>
        public static string msgOperBDErrorModulo {
            get {
                return ResourceManager.GetString("msgOperBDErrorModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación módulos de restricción de acceso.
        /// </summary>
        public static string msgOperBDErrorModuloTitulo {
            get {
                return ResourceManager.GetString("msgOperBDErrorModuloTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea Salir de la Aplicacion?.
        /// </summary>
        public static string msgPrincipalSalir {
            get {
                return ResourceManager.GetString("msgPrincipalSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir de la aplicación.
        /// </summary>
        public static string msgPrincipalSalirTitulo {
            get {
                return ResourceManager.GetString("msgPrincipalSalirTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar esta restricción implica que todos los usuarios, la perderán también.
        ///Quedando este módulo visible a todos.
        ///
        ///¿Desea continuar con la eliminación de la restricción?
        ///(Se cerrará esta ventana para hacer efectivo los cambios).
        /// </summary>
        public static string msgSeguridadEliminarRestriccion {
            get {
                return ResourceManager.GetString("msgSeguridadEliminarRestriccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación de restricción global.
        /// </summary>
        public static string msgSeguridadEliminarRestriccionTitulo {
            get {
                return ResourceManager.GetString("msgSeguridadEliminarRestriccionTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se ha asignado la restricción seleccionada al rol.
        /// </summary>
        public static string msgSeguridadRestriccionRepetida {
            get {
                return ResourceManager.GetString("msgSeguridadRestriccionRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restricción asignada.
        /// </summary>
        public static string msgSeguridadRestriccionRepetidaTitulo {
            get {
                return ResourceManager.GetString("msgSeguridadRestriccionRepetidaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione el usuario para aplicar la acción..
        /// </summary>
        public static string msgSeleccionarUsuario {
            get {
                return ResourceManager.GetString("msgSeleccionarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no identificado.
        /// </summary>
        public static string msgSeleccionarUsuarioTitulo {
            get {
                return ResourceManager.GetString("msgSeleccionarUsuarioTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando elementos de la aplicación....
        /// </summary>
        public static string msgSplashCargandoElementos {
            get {
                return ResourceManager.GetString("msgSplashCargandoElementos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando opciones generales de la aplicación....
        /// </summary>
        public static string msgSplashCargandoOpcsGen {
            get {
                return ResourceManager.GetString("msgSplashCargandoOpcsGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando conexión BD....
        /// </summary>
        public static string msgSplashCheckBD {
            get {
                return ResourceManager.GetString("msgSplashCheckBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando acceso a internet....
        /// </summary>
        public static string msgSplashCheckInternet {
            get {
                return ResourceManager.GetString("msgSplashCheckInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error en la carga de la aplicación.
        ///Inténtelo de nuevo más tarde..
        /// </summary>
        public static string msgSplashErrorCarga {
            get {
                return ResourceManager.GetString("msgSplashErrorCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la carga de la aplicación..
        /// </summary>
        public static string msgSplashErrorCargaTitulo {
            get {
                return ResourceManager.GetString("msgSplashErrorCargaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha bloqueado el terminal.
        /// </summary>
        public static string msgTerminalBloqueado {
            get {
                return ResourceManager.GetString("msgTerminalBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este terminal ha sido bloqueado. Transcurridos {0} minutos y {1} segundos será desbloqueado.
        /// </summary>
        public static string msgTerminalBloqueadoTiempo {
            get {
                return ResourceManager.GetString("msgTerminalBloqueadoTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El terminal volverá a estar disponible en ... {0} m. {1} s..
        /// </summary>
        public static string msgTerminalDisponibleTiempo {
            get {
                return ResourceManager.GetString("msgTerminalDisponibleTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error datos usuarios, error BD:.
        /// </summary>
        public static string msgUsuariosErrorDatosBD {
            get {
                return ResourceManager.GetString("msgUsuariosErrorDatosBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string msgUsuariosErrorDatosBDTitulo {
            get {
                return ResourceManager.GetString("msgUsuariosErrorDatosBDTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general datos usuarios, error BD:.
        /// </summary>
        public static string msgUsuariosErrorDatosGeneralBD {
            get {
                return ResourceManager.GetString("msgUsuariosErrorDatosGeneralBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana .
        /// </summary>
        public static string msgVentana {
            get {
                return ResourceManager.GetString("msgVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap profile {
            get {
                object obj = ResourceManager.GetObject("profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap profile1 {
            get {
                object obj = ResourceManager.GetObject("profile1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap profle {
            get {
                object obj = ResourceManager.GetObject("profle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap roadblock {
            get {
                object obj = ResourceManager.GetObject("roadblock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SaveAll {
            get {
                object obj = ResourceManager.GetObject("SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SaveAsHH {
            get {
                object obj = ResourceManager.GetObject("SaveAsHH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap security {
            get {
                object obj = ResourceManager.GetObject("security", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TileVertically_2065_32 {
            get {
                object obj = ResourceManager.GetObject("TileVertically_2065_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TileWindowsHorizontallyHS {
            get {
                object obj = ResourceManager.GetObject("TileWindowsHorizontallyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unlocked {
            get {
                object obj = ResourceManager.GetObject("unlocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
